---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 32264.
--- DateTime: 2026/5/21 21:16
---
local productId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:product:stock:' .. productId
local orderKey = 'seckill:product:order:' .. productId

if(tonumber(redis.call('get',stockKey))<=0) then
    return 1
end
if(redis.call('sismember',orderKey,userId)==1) then
    return 2
end
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)

-- 【已废弃】Redis Stream 方案，消息发送已迁移到 Java 层通过 RocketMQ 发送
-- redis.call('xadd','stream:order','*','userId',userId,'productId',productId,'id',orderId)
return 0