---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 32264.
--- DateTime: 2026/5/20 15:27
---
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0